from django.urls import path
from . import views
from .views import help_view, register_member, activate_account

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate'),
    path("ajax/zonas/", views.ajax_zonas_by_sector, name="ajax_zonas_by_sector"),
    path("ajax/grupos/", views.ajax_grupos_by_zona, name="ajax_grupos_by_zona"),
    path("perfil/", views.profile, name="profile"),
    path("perfil/", views.my_profile, name="my_profile"),
    path("perfil/editar/", views.edit_my_profile, name="edit_my_profile"),
    path("miembros/<int:user_id>/", views.member_profile, name="member_profile"),
    path("members/division-national/", views.members_division_national_list, name="members_division_national_list"),
    path("members/division-national/export/", views.members_division_national_export, name="members_division_national_export"),
    path("home/banners/", views.manage_banners, name="manage_banners"),
    path("home/banners/nuevo/", views.create_banner, name="create_banner"),
    path("home/banners/<int:banner_id>/editar/", views.edit_banner, name="edit_banner"),
    path("home/banners/<int:banner_id>/eliminar/", views.delete_banner, name="delete_banner"),
    path("home/actividades/", views.manage_events, name="manage_events"),
    path("home/actividades/nueva/", views.create_event, name="create_event"),
    path("home/actividades/<int:event_id>/editar/", views.edit_event, name="edit_event"),
    path("home/actividades/<int:event_id>/eliminar/", views.delete_event, name="delete_event"),
    path("fortuna/", views.fortuna_home, name="fortuna_home"),
    path("fortuna/material/", views.fortuna_material, name="fortuna_material"),
    path("fortuna/ediciones/", views.fortuna_ediciones, name="fortuna_ediciones"),
    path("fortuna/comprar/", views.fortuna_comprar, name="fortuna_comprar"),
    path("fortuna/compradores/", views.fortuna_compradores, name="fortuna_compradores"),
    path("fortuna/pdf/<int:issue_id>/", views.fortuna_pdf, name="fortuna_pdf"),
    path("fortuna/compradores/export/", views.fortuna_compradores_export, name="fortuna_compradores_export"),
    path("ayuda/", help_view, name="help"),
    path("accounts/fortuna/admin/compras/", views.fortuna_admin_purchases, name="fortuna_admin_purchases"),
    path("fortuna/solicitudes/", views.fortuna_admin_purchases, name="fortuna_admin_purchases"),
    path("divisiones/", views.divisions_index, name="divisions_index"),
    path("divisiones/<slug:division>/", views.division_home, name="division_home"),
    path("register/", views.register_member, name="register"),
    path("activate/<uidb64>/<token>/", views.activate_account, name="activate"),
    path("noticias/", views.news_list, name="news_list"),
    path("noticias/<int:pk>/", views.news_detail, name="news_detail"),

]
