# Generated by Django 6.0 on 2025-12-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('directiva', 'Directiva'), ('resp_sector', 'Responsable sector / región'), ('resp_zona', 'Responsable zona'), ('resp_grupo', 'Responsable grupo'), ('miembro', 'Miembro')], default='miembro', max_length=20),
        ),
    ]
