# Generated by Django 6.0 on 2025-12-11 21:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha aporte')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('contribution_type', models.CharField(choices=[('regular', 'Contribución regular'), ('especial', 'Contribución especial')], default='regular', max_length=20, verbose_name='Tipo de contribución')),
                ('note', models.TextField(blank=True, default='', verbose_name='Nota interna')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='Confirmado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Contribución',
                'verbose_name_plural': 'Contribuciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto informado')),
                ('deposit_date', models.DateField(verbose_name='Fecha de depósito')),
                ('receipt', models.FileField(upload_to='contribuciones/comprobantes/', verbose_name='Comprobante de depósito')),
                ('note', models.TextField(blank=True, default='', verbose_name='Comentario adicional')),
                ('family_distribution', models.TextField(blank=True, default='', verbose_name='Distribución entre miembros de la familia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que informa')),
            ],
            options={
                'verbose_name': 'Informe de contribución',
                'verbose_name_plural': 'Informes de contribución',
                'ordering': ['-created_at'],
            },
        ),
    ]
