# Generated by Django 6.0 on 2025-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(default='RUT-DEFAULT', max_length=12, unique=True, verbose_name='RUT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributionreport',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='contribuciones/comprobantes/', verbose_name='Comprobante de depósito'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='apellido'),
        ),
    ]
