# Generated by Django 6.0 on 2025-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_household_householdmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionreport',
            name='distribution',
            field=models.JSONField(blank=True, null=True, verbose_name='Distribución familiar'),
        ),
    ]
