# Generated by Django 6.0 on 2025-12-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contributionreport_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.household'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='relationship',
            field=models.CharField(choices=[('head', 'Jefe/a de hogar'), ('spouse', 'Esposo/a'), ('child', 'Hijo/a'), ('sibling', 'Hermano/a'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='householdmember',
            unique_together={('household', 'user')},
        ),
        migrations.CreateModel(
            name='ContributionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='accounts.contributionreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
