# Generated by Django 6.0 on 2025-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_householdmember_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionreport',
            name='family_distribution',
            field=models.TextField(blank=True, default='', verbose_name='Distribución (texto)'),
        ),
    ]
