# Generated by Django 6.0 on 2025-12-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_contributionreport_family_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['zona__sector__name', 'zona__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_only_family_member',
            field=models.BooleanField(default=False, verbose_name='Único miembro de su familia'),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.grupo', verbose_name='Grupo'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='accounts.sector')),
            ],
            options={
                'ordering': ['sector__name', 'name'],
                'unique_together': {('sector', 'name')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='accounts.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('zona', 'name')},
        ),
    ]
