# Generated by Django 6.0 on 2025-12-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
    ]
