# Generated by Django 6.0 on 2025-12-19 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortunaIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='fortuna/covers/')),
                ('material_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_public_archive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='FortunaPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.fortunaissue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortuna_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('issue', 'user')},
            },
        ),
    ]
