# Generated by Django 6.0 on 2025-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortunaissue',
            name='material_pdf',
            field=models.FileField(blank=True, null=True, upload_to='fortuna/pdfs/'),
        ),
    ]
