# Generated by Django 6.0 on 2025-12-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_fortunaissue_material_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortunapurchase',
            name='deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de depósito'),
        ),
        migrations.AddField(
            model_name='fortunapurchase',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='fortunapurchase',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='fortuna/receipts/', verbose_name='Comprobante'),
        ),
        migrations.AddField(
            model_name='fortunapurchase',
            name='reject_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo rechazo'),
        ),
    ]
