# Generated by Django 6.0 on 2025-12-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_fortunapurchase_deposit_date_fortunapurchase_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('djm', 'División Juvenil Masculina (DJM)'), ('djf', 'División Juvenil Femenina (DJF)'), ('caballeros', 'División Caballeros'), ('damas', 'División Damas')], max_length=20, null=True, verbose_name='División'),
        ),
    ]
