# Generated by Django 6.0 on 2025-12-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_division_national_leader',
            field=models.BooleanField(default=False, verbose_name='Responsable nacional de división'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_division_national_vice',
            field=models.BooleanField(default=False, verbose_name='Vice responsable nacional de división'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_division',
            field=models.CharField(blank=True, choices=[('djm', 'División Juvenil Masculina (DJM)'), ('djf', 'División Juvenil Femenina (DJF)'), ('caballeros', 'División Caballeros'), ('damas', 'División Damas')], help_text='Si es responsable nacional, indica qué división lidera (DJM/DJF/Caballeros/Damas).', max_length=20, null=True, verbose_name='División nacional que lidera'),
        ),
    ]
