# Generated by Django 6.0 on 2025-12-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_is_division_national_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division_national_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_division_national_leader',
            field=models.BooleanField(default=False),
        ),
    ]
