# Generated by Django 6.0 on 2025-12-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_division_national_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_division_national_leader',
            field=models.BooleanField(default=False, verbose_name='Responsable nacional de división'),
        ),
    ]
