# Generated by Django 6.0 on 2025-12-22 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_is_division_national_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('djm', 'DJM'), ('djf', 'DJF'), ('caballeros', 'Caballeros'), ('damas', 'Damas')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='division_posts/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
