# Generated by Django 6.0 on 2025-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_divisionpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_division',
            field=models.CharField(blank=True, choices=[('djm', 'División Juvenil Masculina (DJM)'), ('djf', 'División Juvenil Femenina (DJF)'), ('caballeros', 'División Caballeros'), ('damas', 'División Damas')], help_text='Si es responsable/vice nacional, indica qué división lidera (DJM/DJF/Caballeros/Damas).', max_length=20, null=True, verbose_name='División nacional que lidera'),
        ),
    ]
