# Generated by Django 6.0 on 2025-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_national_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionpost',
            options={'ordering': ['-priority', '-event_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='divisionpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='divisionpost',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='divisionpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
