# Generated by Django 6.0 on 2025-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_divisionpost_options_divisionpost_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisionpost',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.RenameField(
            model_name='divisionpost',
            old_name='is_upcoming',
            new_name='is_featured',
        ),
        migrations.RemoveField(
            model_name='divisionpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='divisionpost',
            name='kind',
            field=models.CharField(choices=[('news', 'Noticia / Aviso'), ('activity', 'Actividad')], default='news', max_length=20),
        ),
        migrations.AlterField(
            model_name='divisionpost',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='divisionpost',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
