# Generated by Django 6.0 on 2026-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_divisionpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('scope', models.CharField(choices=[('general', 'General SGI'), ('chile', 'Chile')], default='general', max_length=20, verbose_name='Ámbito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fecha importante',
                'verbose_name_plural': 'Fechas importantes',
                'ordering': ['-priority', 'date'],
            },
        ),
    ]
