# Generated by Django 6.0 on 2026-01-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_importantdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('body', models.TextField(blank=True, verbose_name='Contenido')),
                ('target', models.CharField(choices=[('global', 'Todos (Global)'), ('sector', 'Sector / Región'), ('zona', 'Zona'), ('grupo', 'Grupo')], default='global', max_length=20, verbose_name='Audiencia')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Destacado')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Desde')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.grupo')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sector')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.zona')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-is_pinned', '-priority', '-created_at'],
            },
        ),
    ]
