# Generated by Django 6.0 on 2026-01-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/', verbose_name='Imagen (opcional)'),
        ),
    ]
