# Generated by Django 6.0 on 2026-01-05 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_notice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Bajada / Resumen')),
                ('body', models.TextField(blank=True, default='', verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagen (opcional)')),
                ('scope', models.CharField(choices=[('general', 'General SGI'), ('chile', 'Chile')], default='general', max_length=20, verbose_name='Ámbito')),
                ('target', models.CharField(choices=[('global', 'Todos (Global)'), ('sector', 'Sector / Región'), ('zona', 'Zona'), ('grupo', 'Grupo')], default='global', max_length=20, verbose_name='Audiencia')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Destacado')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.grupo')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sector')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.zona')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-is_pinned', '-priority', '-published_at', '-created_at'],
            },
        ),
    ]
