# Generated by Django 6.0 on 2026-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='Fuente (URL)'),
        ),
    ]
