# Generated by Django 6.0 on 2026-01-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_newspost_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible para todos (público)'), ('resp_sector', 'Solo responsables de sector / región'), ('resp_zona', 'Solo responsables de zona'), ('resp_any', 'Responsables (sector o zona)')], default='public', max_length=20),
        ),
    ]
