# Generated by Django 6.0 on 2026-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_event_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_divisions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible para todos (público)'), ('custom', 'Visible para selección (roles/divisiones)')], default='public', max_length=20),
        ),
    ]
