# Generated by Django 6.0 on 2026-01-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_event_target_divisions_event_target_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_reports_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='contributionreport',
            name='reported_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_reports_for', to=settings.AUTH_USER_MODEL, verbose_name='Reportado para'),
        ),
    ]
