# Generated by Django 6.0 on 2026-01-07 18:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_contributionreport_reported_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fortunapurchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='fortunapurchase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fortunapurchase',
            name='access_end',
            field=models.DateField(default=datetime.date(2026, 1, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fortunapurchase',
            name='access_start',
            field=models.DateField(default=datetime.date(2026, 1, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fortunapurchase',
            name='plan',
            field=models.CharField(choices=[('trim', 'Trimestral ($12.000)'), ('sem', 'Semestral ($24.000)'), ('anual', 'Anual ($48.000)')], default=datetime.date(2026, 1, 7), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fortunapurchase',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fortuna_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fortunapurchase',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fortunapurchase',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fortunapurchase',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='fortuna/receipts/'),
        ),
        migrations.AlterField(
            model_name='fortunapurchase',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
