# Generated by Django 6.0 on 2026-01-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_fortunapurchase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortunaIssuePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='fortuna/pages/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='accounts.fortunaissue')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('issue', 'page_number')},
            },
        ),
    ]
