# Generated by Django 5.2.10 on 2026-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_fortunaissuepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmember',
            name='relationship',
            field=models.CharField(choices=[('head', 'Titular del Gohonzon'), ('spouse', 'Esposo/a'), ('child', 'Hijo/a'), ('sibling', 'Hermano/a'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_division',
            field=models.CharField(blank=True, choices=[('djm', 'División Juvenil Masculina (DJM)'), ('djf', 'División Juvenil Femenina (DJF)'), ('caballeros', 'División Caballeros'), ('damas', 'División Damas'), ('ds', 'División de Sucesores (DS)')], help_text='Si es responsable/vice nacional, indica qué división lidera (incluye DS).', max_length=20, null=True, verbose_name='División nacional que lidera'),
        ),
    ]
